## 🎯 Problem Statement (MovieLens Dataset)

#####  In the modern digital entertainment landscape, users face a constant challenge: what to watch next? With 'thousands of movie options available on various streaming platforms, making a decision becomes difficult without personalized guidance. Generic `Top 10` lists or trending movies often fail to reflect the unique tastes of individual users.

##### To solve this, we aim to build an **intelligent movie recommendation system** that uses the MovieLens dataset—a widely-used benchmark dataset containing millions of movie ratings provided by real users. The MovieLens dataset offers a rich foundation to analyze user preferences, movie metadata (titles, genres, release dates), and rating behaviors.

##### The key challenge lies in extracting valuable insights from this large and sparse user-item interaction matrix, and then transforming those insights into meaningful, personalized suggestions. A system that can learn from both user behavior patterns and movie features is critical to improving user satisfaction and engagement.

##### The goal is to build a solution that:
  - Understands user preferences through historical ratings.
  - Explores the content side (genre, title, etc.) to recommend similar movies.
  - Uses hybrid recommendation models to combine collaborative filtering and content-based filtering.
  - Can be deployed as an interactive application with real-time suggestions and updates.

<div style="display: flex; justify-content: center;">
  <img src="https://user-images.githubusercontent.com/86877457/132905471-3ef27af4-ecc6-44bf-a47c-5ccf2250410c.jpg" style="width:100%; max-width:1000px;">
</div>

## ✅ Project Objectives (Tailored for MovieLens Dataset)

#### This project aims to develop a feature-rich movie recommendation engine using the MovieLens dataset, leveraging its rich user-movie rating data and metadata to drive powerful, personalized suggestions. Our objectives include:

- Data Acquisition & Understanding:
    -  Load and explore the MovieLens dataset (e.g., 100k, 1M, or 20M versions).
    - Analyze user behavior (e.g., rating frequency, genre preference).
    - Understand data sparsity and user-item interaction distribution.

- Data Preprocessing & Feature Engineering:
    - Clean and preprocess data: handle missing values, duplicates, and anomalies.
    - Engineer content features: one-hot encoding of genres, TF-IDF for movie titles/descriptions.
    - Create user profiles and similarity matrices for collaborative filtering.


- Modeling Techniques:
    -  Collaborative Filtering:
        Use algorithms like Singular Value Decomposition (SVD) and Alternating Least Squares (ALS) to identify latent patterns.
    -  Content-Based Filtering:
        Recommend based on genre similarity and textual similarity (e.g., cosine similarity on TF-IDF vectors).
    - Hybrid Approaches:
        Combine collaborative and content-based strategies to enhance prediction accuracy.


- Evaluation and Optimization:
    - Split the dataset using techniques like time-aware splitting or leave-one-out.
    - Evaluate models with metrics like RMSE, MAE, Precision@K, Recall@K, NDCG@K.
    - Perform hyperparameter tuning to optimize model performance.

- Deployment and Integration:
    - Develop a backend API using Flask or FastAPI that exposes /recommend endpoints.
    - Create an interactive frontend using Streamlit that allows users to:
        - Select user IDs or favorite movies.
        - View real-time movie recommendations.
    -  Track and version experiments with MLflow and manage data pipelines with DVC.


- Monitoring, Feedback, and Improvement:
    - Design a retraining loop for incorporating new ratings and user feedback.
    - Allow real-time rating input and dynamically adjust recommendations.


- Final Output and Presentation:
    - Document the methodology, model performance, and design decisions.
    - Prepare a demo with a functional user interface and recommendation flow.
    - Publish the codebase with a clear README and deployment instructions.

![photo_2025-04-08_17-56-31.jpg]()

# 🎬 MOVIE RECOMMENDATION SYSTEM (MOVIELENS)  
### 📄 Project Documentation – Table of Contents  

---

## 📌 1. PROJECT FOUNDATION
### 🔧 1.1 System Initialization  
- ✅ Library Imports (`pandas`, `numpy`, `tensorflow`)  
- ⚙️ Environment Configuration  
- 🔁 Version Control Setup  

### 📥 1.2 Data Acquisition  
- 🎞️ MovieLens Dataset Selection (30M)  
- 🔽 Data Download Protocol  
- 🗂️ Storage Architecture  

---

## 🏗️ 2. DATA ENGINEERING  
### 📂 2.1 Data Loading Framework  
- 📊 Ratings Dataset Schema  
- 🎬 Movies Metadata Structure  
- ➕ Auxiliary Data (Tags / Links) Integration  

### 🔍 2.2 Data Quality Assessment  
- 🚫 Missing Value Analysis  
- 🧬 Duplicate Detection System  
- ⏳ Temporal Data Conversion  

### 🔄 2.3 Feature Transformation  
- 🎭 Genre Decomposition Matrix  
- 👥 User-Movie Interaction Grid  
- 📉 Rating Normalization Pipeline  

---

## 📊 3. EXPLORATORY ANALYSIS  
### 📈 3.1 Statistical Profiling  
- 📚 Rating Distribution Analysis  
- 👤 User Engagement Metrics  
- 🌟 Movie Popularity Index  

### 🖼️ 3.2 Visual Analytics  
- 🕒 Temporal Activity Heatmaps  
- 🎼 Genre Popularity Trends  
- ☁️ Content Tag Cloud Visualizations  

---

## 🤖 4. MACHINE LEARNING FRAMEWORK  
### 🧠 4.1 Feature Engineering  
- 🧍 User Preference Vectors  
- 🎥 Movie Attribute Embeddings  
- 🔤 Semantic Title Features (TF-IDF)  

### 🧮 4.2 Recommendation Algorithms  
#### 🔄 Collaborative Filtering  
- 📐 SVD Matrix Factorization  
- 🔁 Alternating Least Squares (ALS)  

#### 🧾 Content-Based Filtering  
- 🎭 Genre Similarity Scoring  
- 🧬 Semantic Content Matching  

#### 🔗 Hybrid Approach  
- ⚖️ Weighted Ensemble Method  
- 🧱 Stacked Recommendation Architecture  

---

## 🛠️ 5. MODEL OPTIMIZATION  
### 📊 5.1 Evaluation Protocol  
- ⏰ Temporal Validation Strategy  
- 📏 Metrics Suite:  
  - 🎯 RMSE / MAE (Prediction Accuracy)  
  - 🧭 NDCG@K (Ranking Quality)  
  - 🔍 Precision@K / Recall@K (Relevance Metrics)  

### 🎯 5.2 Hyperparameter Tuning  
- 📊 Grid Search Configuration  
- 🎲 Randomized Parameter Optimization  

---

## 🚀 6. DEPLOYMENT ARCHITECTURE  
### 🧪 6.1 MLOps Infrastructure  
- 🔍 Experiment Tracking (MLflow)  
- 🧾 Data Versioning (DVC)  

### 🔌 6.2 API Services  
- 🌐 RESTful Recommendation Endpoints  
- 🧰 FastAPI / Flask Backend  

### 💻 6.3 User Interface  
- 📊 Streamlit Dashboard  

---

## 🔍 7. SYSTEM MONITORING  
### 🗂️ 7.1 Feedback Mechanisms  
- 📈 User Interaction Logging  
- 👀 Implicit Feedback Collection  

### ♻️ 7.2 Continuous Improvement  
- 🔁 Model Retraining Schedule  
- ⚠️ Concept Drift Detection  

---

## 📦 8. PROJECT DELIVERABLES  
### 📑 8.1 Technical Documentation  
- 🏗️ System Architecture Diagrams  
- 🧾 API Specifications  

### 🖥️ 8.2 Presentation Materials  
- 📝 Executive Summary  
- 📈 Model Performance Benchmarking  
- 🎥 Demonstration Scenarios  

### 🗃️ 8.3 Repository Structure  
- 🧱 Code Organization  
- 🚀 Deployment Artifacts  

---

## 🌱 9. ENHANCEMENT ROADMAP  
### 🌟 9.1 Advanced Features  
- 🌐 TMDB API Integration  
  - 🎞️ High-Resolution Movie Posters  
  - 🎬 Trailer Embedding System  
  - 🎭 Celebrity Cast Information  

- ❄️ Cold Start Solutions  
  - 🧑‍🤝‍🧑 Demographic Filtering  
  - 📚 Knowledge-Based Recommendations  

### ⚙️ 9.2 Scalability Upgrades  
- ⏱️ Real-Time Recommendation Engine  
- 🧮 Distributed Computing Implementation  

---

**📌 Project Version**: `1.0`  
**🕒 Last Updated**: `8/4/2025`

# 1. PROJECT FOUNDATION


*   1.1 System Initialization
*   1.2 Data Acquisition

1.1.1 Library Imports & Environment Configuration

In [ ]:
!pip install wordcloud

Requirement already satisfied: wordcloud in /usr/local/lib/python3.11/dist-packages (1.9.4)
Requirement already satisfied: numpy>=1.6.1 in /usr/local/lib/python3.11/dist-packages (from wordcloud) (2.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from wordcloud) (11.2.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from wordcloud) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

In [ ]:
# ------------------------------
# 📦 Data Handling & Processing
# ------------------------------
import pandas as pd
import numpy as np
import os
import json
import datetime as dt
from tqdm import tqdm
import requests
from time import sleep

import warnings
warnings.filterwarnings('ignore')

# ------------------------------
# 🔍 Exploratory Data Analysis
# ------------------------------
# import pandas_profiling
from wordcloud import WordCloud


# ------------------------------
# 📊 Visualization
# ------------------------------
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display, HTML
from plotly.subplots import make_subplots
from wordcloud import WordCloud


# ------------------------------
# 🧠 Machine Learning (Scikit-learn)
# ------------------------------
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report,precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import TruncatedSVD


# ------------------------------
# 📚 Recommender Systems (Surprise)
# ------------------------------

from surprise import Dataset, Reader, SVD, KNNBasic
from surprise.model_selection import cross_validate

# ------------------------------
# 🤖 Deep Learning (TensorFlow/Keras)
# ------------------------------
import tensorflow as tf
from tensorflow import keras
from keras.models import Model
from keras.layers import Input, Embedding, Flatten, Dot, Dense, Concatenate, Dropout
from keras.optimizers import Adam

1.2 Data Acquisition

1.2.1 MovieLens Dataset Selection (30M)

In [ ]:
# Download the MovieLens 30M dataset
dataset_url = "https://files.grouplens.org/datasets/movielens/ml-latest.zip"
!wget $dataset_url -O ml-latest.zip

--2025-05-06 13:17:14--  https://files.grouplens.org/datasets/movielens/ml-latest.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 350896731 (335M) [application/zip]
Saving to: ‘ml-latest.zip’

ml-latest.zip       100%[===================>] 334.64M  16.9MB/s    in 22s

2025-05-06 13:17:37 (15.5 MB/s) - ‘ml-latest.zip’ saved [350896731/350896731]

1.2.2 Data Download Protocol & Storage Architecture

In [ ]:
# Unzip the dataset
!unzip ml-latest.zip

Archive:  ml-latest.zip
   creating: ml-latest/
  inflating: ml-latest/tags.csv
  inflating: ml-latest/links.csv
  inflating: ml-latest/README.txt
  inflating: ml-latest/ratings.csv
  inflating: ml-latest/genome-tags.csv
  inflating: ml-latest/genome-scores.csv
  inflating: ml-latest/movies.csv

# 2. DATA ENGINEERING

*   2.1 Data Loading Framework
*   2.2 Data Quality Assessment
*   2.3 Feature Transformation

## 2.1 Data Loading Framework

### 2.1.1 Movies & Rating Dataset **Schema**

---

In [ ]:
# read all datasets from ml folder
ratings = pd.read_csv('ml-latest/ratings.csv')
movies = pd.read_csv('ml-latest/movies.csv')
genome_scores = pd.read_csv('ml-latest/genome-scores.csv')
genome_tags = pd.read_csv('ml-latest/genome-tags.csv')

In [ ]:
links = pd.read_csv('ml-latest/links.csv')
tags = pd.read_csv('ml-latest/tags.csv')

#### 2.1.3 Movies **Metadata** Structure

---

In [ ]:
# convert data to DataFrame
ratings_df = pd.DataFrame(ratings)
movies_df = pd.DataFrame(movies)
links_df = pd.DataFrame(links)
tags_df = pd.DataFrame(tags)
genome_scores_df = pd.DataFrame(genome_scores)
genome_tags_df = pd.DataFrame(genome_tags)

## 2.2  Data Quality Assessment

### 2.2.1 Missing Value Analysis & 2.2.2 Duplicate Detection System


---

#### Rating Datasets

In [ ]:
# print 5 row of rating
ratings_df.head()

   userId  movieId  rating   timestamp
0       1        1     4.0  1225734739
1       1      110     4.0  1225865086
2       1      158     4.0  1225733503
3       1      260     4.5  1225735204
4       1      356     5.0  1225735119

In [ ]:
# print rating shape
ratings_df.shape

(33832162, 4)

In [ ]:
print("The Total Number OF Rating :",ratings_df.shape[0])

The Total Number OF Rating : 33832162

In [ ]:
# print the information
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33832162 entries, 0 to 33832161
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 1.0 GB

In [ ]:
# select the number of decimal number after .
pd.set_option('display.float_format', '{:.2f}'.format)

# Display the summary again with non-scientific formatting
ratings_df.describe().T

,count,mean,std,min,25%,50%,75%,max
userId,33832162.00,165437.98,95341.22,1.00,82953.00,166129.00,247450.00,330975.00
movieId,33832162.00,28313.48,49928.65,1.00,1219.00,3263.00,40491.00,288983.00
rating,33832162.00,3.54,1.06,0.50,3.00,4.00,4.00,5.00
timestamp,33832162.00,1269361676.74,254102317.37,789652004.00,1046717792.00,1264740144.00,1496919379.25,1689843213.00

📊 Summary Statistical

> Add blockquote



- 💡 Insight 1: movieId as an Identifier
The movieId is primarily an identifier, but its wide distribution and gaps suggest the dataset might have been merged or expanded in batches over time. This could lead to some movie IDs being significantly less represented, a classic example of the long-tail distribution common in movie catalogs.

- 💡 Insight 2: Duplication in Titles
Minor duplication in title values hints at possible re-releases, alternate versions, or inconsistent metadata entries. To ensure clean analysis, a deduplication or normalization step is recommended—perhaps by aligning with unique imdbId or tmdbId where available.

- 💡 Insight 3: Dominant Genre – Drama
An early genre analysis shows that Drama is the most common genre. This reflects general trends in movie datasets where dramatic narratives form a substantial proportion of both popular and niche titles.

  The dataset contains 33,832,162 entries representing user ratings on movies. Below is a summary of the key numerical fields:

- 1. User ID
    - Total Users (Count): 33,832,162
    - Mean User ID: 165,437.98
    - Standard Deviation: 95,341.22
    - Minimum ID: 1
    - 25th Percentile: 82,953
    - Median (50th Percentile): 166,129
    - 75th Percentile: 247,450
    - Maximum ID: 330,975

- 2. Movie ID
    - Total Movie Ratings (Count): 33,832,162
    -  Mean Movie ID: 28,313.48
    -  Standard Deviation: 49,928.65
    -  Minimum Movie ID: 1
    -  25th Percentile: 1,219
    -  Median (50th Percentile): 3,263
    - 75th Percentile: 40,491
    - Maximum Movie ID: 288,983

- 3. Rating
    -  Total Ratings: 33,832,162
    -  Average Rating: 3.54
    -  Standard Deviation: 1.06
    -  Minimum Rating: 0.5
    -  25th Percentile: 3.0
    -  Median Rating: 4.0
    - 75th Percentile: 4.0
    - Maximum Rating: 5.0

- 4. Timestamp
    - Total Entries: 33,832,162
    -  Mean Timestamp (Epoch): 1,269,361,676.74
    - Standard Deviation: 254,102,317.37
    - Minimum Timestamp: 789,652,004 → 📅 1995-01-01 approx
    - 25th Percentile: 1,046,717,792 → 📅 2003-04-01 approx
    -  Median Timestamp: 1,264,740,144 → 📅 2010-01-01 approx
    - 75th Percentile: 1,496,919,379 → 📅 2017-06-01 approx
    -  Maximum Timestamp: 1,689,843,213 → 📅 2023-07-20 approx

In [ ]:
# check the null value
print("The Total Number Of Null Value:",ratings_df.isnull().sum().sum())

The Total Number Of Null Value: 0

In [ ]:
# check the Duplicateed
print("The Total Number of Duplicateed Data:",ratings_df.duplicated().sum())

The Total Number of Duplicateed Data: 0

In [ ]:
# number of User in dataset
print("The Total Number of Unique User:",ratings_df["userId"].nunique())

The Total Number of Unique User: 330975

In [ ]:
# number of Movies in dataset
print("The Total Number of Unique Movies:",ratings_df["movieId"].nunique())

The Total Number of Unique Movies: 83239

In [ ]:
# convert timestamp to date time
ratings_df['timestamp'] = pd.to_datetime(ratings_df['timestamp'], unit='s')

In [ ]:
# min and max and std rating
ratings_df["rating"].agg(["min","max","var","mean"])

min    0.50
max    5.00
var    1.13
mean   3.54
Name: rating, dtype: float64

In [ ]:
# check rating have outliers
ratings_df["rating"].value_counts()

rating
4.00    8835955
3.00    6400664
5.00    4957902
3.50    4465001
4.50    3123055
2.00    2146492
2.50    1760733
1.00    1013645
0.50     566306
1.50     562409
Name: count, dtype: int64

In [ ]:
ratings_df.sample(5)

          userId  movieId  rating           timestamp
11295339  111259    79695    0.50 2017-11-13 12:20:20
27299487  266480       23    5.00 1996-05-15 11:42:12
32767567  320224     6324    3.00 2004-02-14 14:00:41
33699422  329753     1997    4.00 2016-07-30 02:12:18
20359900  198797    85438    3.50 2015-12-18 01:10:58

#### Movies datasets

In [ ]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
# movies shape
movies_df.shape

(86537, 3)

In [ ]:
# number movies df
print("Total Number of movies in df",movies_df.shape[0])

Total Number of movies in df 86537

In [ ]:
# diffrrence betweeen movies in movies_df and ratings_df
print("Diffrrence betweeen movies in movies_df and ratings_df :",movies_df.shape[0]-ratings_df["movieId"].nunique())

Diffrrence betweeen movies in movies_df and ratings_df : 3298

In [ ]:
# sample of movies
movies_df.sample(5)

,movieId,title,genres
31604,138446,Come il vento (2013),Drama
47956,174419,The Tattoo (1968),Comedy
25885,124568,Silver River (1948),Drama|Romance|Western
70882,227959,Cut Throat City (2020),Action|Crime|Drama|Thriller
51863,182637,The Second Renaissance Part I (2003),Animation|Sci-Fi

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86537 entries, 0 to 86536
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  86537 non-null  int64
 1   title    86537 non-null  object
 2   genres   86537 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB

In [ ]:
movies_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
movieId,86537.00,NaN,NaN,NaN,155932.82,78037.15,1.00,111443.00,164574.00,211225.00,288983.00
title,86537,86330,Alone (2020),4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
genres,86537,1796,Drama,12246,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Summary Statistical:

- 💡 Insight 1: movieId as an Identifier
The movieId is primarily an identifier, but its distribution suggests that the data may have been merged or appended over time from different batches or datasets. This could explain the wide range of IDs, some of which may be underrepresented due to the long-tail nature of the movie catalog.

- 💡 Insight 2: Duplication in Titles
There seems to be some minor duplication in titles, which could indicate re-releases, remakes, or metadata inconsistencies. This is common in large movie datasets, and it’s worth conducting a deduplication or normalization process to ensure accurate movie representations.

- 💡 Insight 3: Dominant Genre - Drama
Drama is the most frequent genre, appearing in a substantial portion of the

userId:

  -  count: 2,328,315 total entries.
  -  mean: The average userId is 177,666.49.
  -  std: The standard deviation is 82,856.69, -  -  indicating a high variation in user IDs.
  -  min: The minimum userId is 10.00.
  -  25%: The 25th percentile userId is 114,405.00.
  -  50%: The median userId is 215,490.00.
  -  75%: The 75th percentile userId is 215,490.00.
  -  max: The maximum userId is 330,947.00.

movieId:

  -  count: 2,328,315 total entries.
  -  mean: The average movieId is 70,552.80.
  -  std: The standard deviation is 74,024.27, -  -  -  indicating significant variation in movie IDs.
  -  min: The minimum movieId is 1.00.
  -  25%: The 25th percentile movieId is 3,897.00.
  -  50%: The median movieId is 51,077.00.
  -  75%: The 75th percentile movieId is 117,533.00.
  -  max: The maximum movieId is 288,955.00.

timestamp:

  -  count: 2,328,315 total entries.
  -  mean: The average timestamp is 1,522,918,570.41.
  -  std: The standard deviation is 130,854,588.63, -  showing high variability in timestamps.
  -  min: The minimum timestamp is 1,135,429,210.00.
  -  25%: The 25th percentile timestamp is 1,457,996,685.00.
  -  50%: The median timestamp is 1,561,826,361.00.
  max: The maximum timestamp is 1,614,284,000.00.

#### Tags Datasets

In [ ]:
# The number of Null Value
tags_df.isnull().sum()

userId        0
movieId       0
tag          17
timestamp     0
dtype: int64

In [ ]:
# The number of duplicate
print("The Number Of Duplicate:",tags_df.duplicated().sum())

The Number Of Duplicate: 0

In [ ]:
# sample of tags
tags_df.sample(5)

         userId  movieId                  tag   timestamp
681832   128536   151199              glasses  1615746969
1941600  241095        6       Robert De Niro  1359325229
503241    98835    90376        tilda swinton  1523764460
1849845  227088     3717  seen more than once  1168368996
807029   154483     4768        investigation  1590003831

In [ ]:
# Tags shape
tags_df.shape

(2328315, 4)

In [ ]:
# The Total number of userId in tags
print("The Total number of userId in tags",tags_df["userId"].nunique())

The Total number of userId in tags 25280

In [ ]:
# The Total number of userId in tags
print("The Total number have rating not have tags",ratings_df["userId"].nunique() - tags_df["userId"].nunique())

The Total number have rating not have tags 305695

In [ ]:
print("The Total number of links",links_df.shape[0])

The Total number of links 86537

In [ ]:
links_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86537 entries, 0 to 86536
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  86537 non-null  int64
 1   imdbId   86537 non-null  int64
 2   tmdbId   86411 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 2.0 MB

In [ ]:
links_df.describe().T

,count,mean,std,min,25%,50%,75%,max
movieId,86537.00,155932.82,78037.15,1.00,111443.00,164574.00,211225.00,288983.00
imdbId,86537.00,2696384.00,4078415.40,1.00,93811.00,484562.00,3775202.00,28227488.00
tmdbId,86411.00,236310.15,240482.86,2.00,46328.00,136217.00,376285.00,1147612.00

Statistical Summary


- 💡 Insight: The distribution of movieId suggests that this is a system-generated identifier rather than a sequence based on time or popularity. The range reflects extensive growth in the dataset over time.

- 💡 Insight: imdbId values span a very wide range, consistent with the growth of the IMDb catalog over decades. The high standard deviation suggests a mix of both classic and contemporary films.

- 💡 Insight: The tmdbId field shows a similar pattern of growth and diversity. The slight drop in entry count (126 fewer than imdbId) may indicate missing TMDB mappings for some movies, which could be addressed with API lookups or imputation if necessary.

- movieId:

  - count: 86,537 total entries.
  - mean: The average movieId is 155,932.82.
  - std: The standard deviation is 78,037.15, indicating significant variation in movie IDs.
  - min: The minimum movieId is 1.00.
  - 25%: The 25th percentile movieId is 111,443.00.
  - 50%: The median movieId is 164,574.00.
  - 75%: The 75th percentile movieId is 211,225.00.
  - max: The maximum movieId is 288,983.00.


- imdbId:

  - count: 86,537 total entries.
  - mean: The average imdbId is 2,696,384.00.
  - std: The standard deviation is 4,078,415.40, indicating significant variability in IMDB IDs.
  - min: The minimum imdbId is 1.00.
  - 25%: The 25th percentile imdbId is 93,811.00.
  - 50%: The median imdbId is 484,562.00.
  - 75%: The 75th percentile imdbId is 3,775,202.00.
  - max: The maximum imdbId is 28,227,488.00.


- tmdbId:

  - count: 86,411 total entries.
  - mean: The average tmdbId is 236,310.15.
  - std: The standard deviation is 240,482.86, indicating wide variation in tmdb IDs.
  - min: The minimum tmdbId is 2.00.
  - 25%: The 25th percentile tmdbId is 46,328.00.
  - 50%: The median tmdbId is 136,217.00.
  - 75%: The 75th percentile tmdbId is 376,285.00.
  - max: The maximum tmdbId is 1,147,612.00.

In [ ]:
# The Number of Null Value
links_df.isnull().sum()

movieId      0
imdbId       0
tmdbId     126
dtype: int64

In [ ]:
# The Number of Duplicate
print("The Number Of Duplicate:",links_df.duplicated().sum())

The Number Of Duplicate: 0

#### Genome_Score Datasets

In [ ]:
genome_scores_df.head()

   movieId  tagId  relevance
0        1      1       0.03
1        1      2       0.02
2        1      3       0.07
3        1      4       0.06
4        1      5       0.12

In [ ]:
genome_scores_df.shape

(18472128, 3)

In [ ]:
print("The Total number of Genome_score",genome_scores_df.shape[0])

The Total number of Genome_score 18472128

In [ ]:
genome_scores_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18472128 entries, 0 to 18472127
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   movieId    int64
 1   tagId      int64
 2   relevance  float64
dtypes: float64(1), int64(2)
memory usage: 422.8 MB

In [ ]:
genome_scores_df.describe().T

,count,mean,std,min,25%,50%,75%,max
movieId,18472128.00,64215.29,72459.29,1.00,4528.75,32921.00,108296.25,288167.00
tagId,18472128.00,564.50,325.63,1.00,282.75,564.50,846.25,1128.00
relevance,18472128.00,0.11,0.15,0.00,0.02,0.05,0.13,1.00

🔍 Summary Statistical
- 💡 Insight: Most relevance scores are concentrated around earlier movie IDs, possibly because those movies are more tagged and known by the community.
- 💡 Insight: Tag usage is well distributed, which is useful for diverse content tagging and content-based recommendation.
- 💡 Insight: Tag relevance scores help indicate which tags strongly apply to which movies. A high number of low scores is expected—only a few tags describe any given movie well.

- 🎞️ movieId
     - count = 18,472,128: A large number of tag associations across movies.
     - mean = 64,215.29, std = 72,459.29: IDs are not sequential and span a wide range.
     - min = 1.00, max = 288,167.00: IDs range broadly, again suggesting movie records accumulated over time.
     - 25% = 4,528.75, 50% = 32,921.00, 75% = 108,296.25: Most tags are assigned to lower-numbered movie IDs (older/popular ones), but the long tail continues into higher IDs.

- 🏷️ tagId
    - count = 18,472,128
    - mean = 564.50, std = 325.63: IDs are centered but have spread—reflecting many unique tags.
    -  min = 1.00, max = 1,128.00: There are 1,128 different tags.
    - 25% = 282.75, 50% = 564.50, 75% = 846.25: Tag IDs are evenly distributed.


- 📈 relevance
    - count = 18,472,128
    - mean = 0.11, std = 0.15: Most tags have low relevance for a given movie.
    - min = 0.00, max = 1.00
    - 25% = 0.02, 50% = 0.05, 75% = 0.13
    - Relevance scores are skewed toward low values, with only a few tags being very relevant to most movies.

In [ ]:
# The number of Null Value
print("The number of Null Value:",genome_scores_df.isnull().sum().sum())

The number of Null Value: 0

In [ ]:
# The number of Duplicate
print("The number of Null Value:",genome_scores_df.duplicated().sum())

The number of Null Value: 0

In [ ]:
print("number of movies in tage",genome_scores_df["movieId"].nunique())

number of movies in tage 16376

In [ ]:
genome_tags_df.sample(5)

      tagId                  tag
243     244   computer animation
1004   1005          sword fight
69       70           apocalypse
56       57              amnesia
232     233  comic book adaption

In [ ]:
genome_tags_df.shape

(1128, 2)

In [ ]:
print("The Total nimber of genome ",genome_tags_df.shape[0])

The Total nimber of genome  1128

In [ ]:
genome_tags_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tagId   1128 non-null   int64
 1   tag     1128 non-null   object
dtypes: int64(1), object(1)
memory usage: 17.8+ KB

Summary Statistical

- 💡 Insight 1: Rich Vocabulary
With over 1,000 unique tags, the dataset offers a wide and diverse vocabulary useful for fine-grained movie classification or content-based filtering.

- 💡 Insight 2: Readiness for Text Analysis
The tags are in a clean format (object dtype), which makes them suitable for NLP tasks such as vectorization, clustering, or semantic similarity analysis.

- 💡 Insight 3: No Missing Data
Both columns are fully populated, which ensures integrity for mapping or feature engineering processes in machine learning workflows.

- tagId:

    - Type: int64
    - Non-Null Count: 1,128
    - Description: Numeric identifier for each tag.
    - Uniqueness: All tagId values are unique, representing distinct tags.

- tag:

    - Type: object (string)
    - Non-Null Count: 1,128
    - Description: Textual label or keyword associated with a movie.
    - Examples: "romantic", "sci-fi", "based on a true story"
    - Usage: Used to classify movies by themes, genres, or characteristics

In [ ]:
genome_tags_df.describe().T

        count   mean    std  min    25%    50%    75%     max
tagId 1128.00 564.50 325.77 1.00 282.75 564.50 846.25 1128.00

### 2.2.3 Temporal Data Conversion

In [ ]:
# Calculate rating count and average rating per user
user_stats = ratings.groupby("userId").agg(
    rating_count=("rating", "count"),
    rating_avg=("rating", "mean")
).reset_index()

In [ ]:
# Calculate average rating per movie
movie_stats = ratings.groupby("movieId").agg(
    ave_rating=("rating", "mean")
).reset_index()

In [ ]:
# Extract year from the movie title
movies["year"] = movies["title"].str.extract(r"\((\d{4})\)")

In [ ]:
# Convert genres into separate columns
genres_expanded = movies["genres"].str.get_dummies(sep="|")
movies = pd.concat([movies, genres_expanded], axis=1)

In [ ]:
# Merge movie statistics with the movies dataset
movies = movies.merge(movie_stats, on="movieId", how="left")

In [ ]:
# Merge user statistics with the ratings dataset
ratings = ratings.merge(user_stats, on="userId", how="left")

In [ ]:
ratings["timestamp"] = pd.to_datetime(ratings['timestamp'], unit='s')

In [ ]:
ratings.sample(10)

,userId,movieId,rating,timestamp,rating_count,rating_avg
29411885,287269,994,3.00,2003-02-21 23:04:48,113,3.68
30764439,300830,1374,5.00,2001-11-10 21:41:50,512,3.56
26424409,257939,780,4.00,2010-06-18 01:04:08,168,3.71
33576475,328670,186,1.00,2005-12-14 17:03:16,244,2.76
25483791,248542,6,4.00,1996-11-19 11:40:45,94,3.22
4217786,41224,1676,2.50,2008-08-23 23:06:22,212,3.12
41820,442,919,4.00,1999-11-06 22:06:19,251,3.99
27355641,267046,33660,2.00,2011-04-03 12:52:35,86,3.31
15174074,149209,1225,4.50,2003-08-21 18:10:16,343,4.15
8957675,87935,5459,2.50,2018-07-28 04:13:43,254,3.68

In [ ]:
ratings[ratings["userId"] == 21697]

         userId  movieId  rating           timestamp  rating_count  rating_avg
2218060   21697        1    3.00 2021-08-21 06:09:43           522        3.31
2218061   21697       32    3.00 2021-05-13 09:48:56           522        3.31
2218062   21697       50    4.00 2021-05-06 06:33:22           522        3.31
2218063   21697       70    5.00 2021-05-06 05:07:58           522        3.31
2218064   21697      101    1.50 2021-05-06 07:03:53           522        3.31
...         ...      ...     ...                 ...           ...         ...
2218577   21697   251606    2.50 2021-07-26 14:32:37           522        3.31
2218578   21697   253960    3.50 2021-07-24 14:49:32           522        3.31
2218579   21697   253976    2.50 2021-08-21 09:18:52           522        3.31
2218580   21697   258929    2.50 2021-09-29 12:37:14           522        3.31
2218581   21697   262755    0.50 2021-11-13 07:08:26           522        3.31

[522 rows x 6 columns]

In [ ]:
ratings.to_csv("ratings_with_stats.csv", index=False)
movies.to_csv("movies_with_stats.csv", index=False)

In [ ]:
print(ratings.shape)
print(movies.shape)
print(tags.shape)
print(links.shape)
print(genome_scores.shape)
print(genome_tags.shape)

(33832162, 6)
(86537, 25)
(2328315, 4)
(86537, 3)
(18472128, 3)
(1128, 2)

In [ ]:
print(ratings.columns)
print(movies.columns)

Index(['userId', 'movieId', 'rating', 'timestamp', 'rating_count',
       'rating_avg'],
      dtype='object')
Index(['movieId', 'title', 'genres', 'year', '(no genres listed)', 'Action',
       'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary',
       'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western', 'ave_rating'],
      dtype='object')

## 2.3 Feature Transformation

#### 2.3.1 Genre Decomposation Matrix




---

In [ ]:
# Combine tags per movie into a single string (handling NaNs)
tags['tag'] = tags['tag'].astype(str)  # Convert to string in case of NaNs
movie_tags = tags.groupby("movieId")['tag'].apply(lambda x: " ".join(x)).reset_index()
movie_tags.rename(columns={"tag": "all_tags"}, inplace=True)

In [ ]:
# Merge the tags into the movies dataset
movies_with_tags = movies.merge(movie_tags, on="movieId", how="left")

In [ ]:
# Fill missing tag data
movies_with_tags["all_tags"] = movies_with_tags["all_tags"].fillna("")

In [ ]:
movies_full = movies_with_tags.copy();

In [ ]:
# Merge movie data
movies_full = movies_full.merge(links, on='movieId', how='left')

In [ ]:
movies_full.shape

(86537, 28)

In [ ]:
movies_full.to_csv("movies_full.csv", index=False)

#### 2.3.1 User-Movies Interaction Grid

In [ ]:
# Load the data
ratings = pd.read_csv("ratings_with_stats.csv")
movies_full = pd.read_csv("movies_full.csv")

In [ ]:
print(ratings.columns)
print(movies_full.columns)

In [ ]:
ratings_sample = ratings.sample(n=1_000_000, random_state=42)

In [ ]:
# save the sample
ratings_sample.to_csv("ratings_sample.csv", index=False)

In [ ]:
# Load the data
ratings = pd.read_csv("ratings_sample.csv")
movies_full = pd.read_csv("movies_full.csv")

In [ ]:
# Merge ratings with additional information like rating count and average for 'rating'
rating_full = pd.merge(
    ratings_sample[['userId', 'movieId', 'rating', 'timestamp', 'rating_count', 'rating_avg']],
                  movies_full[['movieId', 'title']],
                  on='movieId', how='left')

In [ ]:
movies_full.isnull().sum()

In [ ]:
API_KEY = '193db7f'

# Function to fetch year by title
def fetch_year_from_omdb(title):
    params = {
        't': title,
        'apikey': API_KEY
    }
    try:
        response = requests.get("http://www.omdbapi.com/", params=params)
        data = response.json()
        if data.get('Response') == 'True':
            return data.get('Year')
    except:
        pass
    return None

In [ ]:
# Fill missing years
def fill_missing_years(df):
    missing_indices = df[df['year'].isna()].index
    for i in missing_indices:
        title = df.at[i, 'title']
        year = fetch_year_from_omdb(title)
        df.at[i, 'year'] = year
        print(f"Filled year for '{title}': {year}")
        sleep(1)  # OMDb rate limiting
    return df

In [ ]:
# convert year to numeric and handle errors
movies_full['year'] = pd.to_numeric(movies_full['year'], errors='coerce')

In [ ]:
# The is steal null value in year ,so i will fill with zero
movies_full["year"].fillna(0, inplace=True)

In [ ]:
# The existing a null value in tmdbld ,but it not import
movies_full.isnull().sum()

In [ ]:
# Rename columns (optional cleanup if needed)
movies_full.columns = movies_full.columns.str.strip().str.lower().str.replace(' ', '_')

In [ ]:
# Handle genres column (if exists)
if 'genres' in movies_full.columns:
    movies_full['genres'] = movies_full['genres'].fillna('Unknown')
    movies_full['genres'] = movies_full['genres'].apply(lambda x: x.split('|') if isinstance(x, str) else ['Unknown'])

In [ ]:
# Convert titles to string
movies_full['title'] = movies_full['title'].astype(str)

In [ ]:
# we will read the new datasets
ratings_full = pd.read_csv("rating_full (1).csv")
movies_full = pd.read_csv("movies_full (1).csv")

In [ ]:
# There is problem in rating_count and rating_avg because this value for all data no sample
ratings_full.drop(columns=["rating_count","rating_avg"], inplace=True)

In [ ]:
# Merge user statistics with the ratings dataset
ratings_full = ratings_full.merge(user_stats, on="userId", how="left")

In [ ]:
ratings_full["movieId"].isin(movies_full["movieid"]).all()

In [ ]:
ratings_full.drop(columns=["Unnamed: 0.1","Unnamed: 0"],inplace = True)

In [ ]:
ratings_full = ratings_full.merge(user_stats, on="userId", how="left")

In [ ]:
ratings_full["rating_avg"] = ratings_full["rating_avg"].round(2)

In [ ]:
# make sure all raing movies have rating in movies
zero_avg_movies = movies_full[movies_full["avg_rating"] != 0]["movieId"].unique()
existing_movies_in_ratings = np.isin(zero_avg_movies, ratings_full["movieId"].unique()).all()
print("make sure all raing movies have avg rating in movies:",existing_movies_in_ratings)

In [ ]:
ratings_full.to_csv("rating.csv", index=False)
movies_full.to_csv("movies.csv", index=False)

In [ ]:
movies_full.rename(columns={"avg_rating": "movies_avg_rating"}, inplace=True)

In [ ]:
ratings_full.rename(
    columns={
        "rating": "user_rating",
        "rating_count": "user_rating_count",
        "rating_avg": "user_rating_avg",
    },
    inplace=True,
)

In [ ]:
df = ratings_full.merge(movies_full, on="movieId", how="left")

In [ ]:
df.drop(columns=["title_y", "year_y",], inplace=True)
df.rename(columns={"title_x": "title","year_x":"year"}, inplace=True)

In [ ]:
# save the sample df after update
df.to_csv("df1.csv", index=False)

In [ ]:
df = pd.read_csv("df1.csv")

In [ ]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'userId', 'movieId', 'user_rating',
       'movie_title', 'user_rating_count', 'user_rating_avg', 'genres',
       '(no genres listed)', 'Action', 'Adventure', 'Animation', 'Children',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
       'Horror', 'IMAX', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller',
       'War', 'Western', 'imdbId', 'tmdbId', 'movies_avg_rating', 'year',
       'month', 'day', 'hour', 'minute', 'movie_year'],
      dtype='object')

In [ ]:
df.sample(5)

,Unnamed: 0.1,Unnamed: 0,userId,movieId,user_rating,movie_title,user_rating_count,user_rating_avg,genres,(no genres listed),...,Western,imdbId,tmdbId,movies_avg_rating,year,month,day,hour,minute,movie_year
445475,445476,445476,147351,593,3,"Silence of the Lambs, The",2,2.00,Crime|Horror|Thriller,0,...,0,102926,274,4.15,2016,2,28,23,40,1991.0
299656,299656,299656,27337,116887,3,Exodus: Gods and Kings,39,3.40,Action|Adventure|Drama,0,...,0,1528100,147441,2.91,2016,4,21,13,21,2014.0
54795,54795,54795,163051,648,3,Mission: Impossible,2,3.50,Action|Adventure|Mystery|Thriller,0,...,0,117060,954,3.38,2008,3,14,9,59,1996.0
627358,627360,627360,109328,5618,5,Spirited Away (Sen to Chihiro no kamikakushi),26,3.46,Adventure|Animation|Fantasy,0,...,0,245429,129,4.21,2005,3,25,3,12,2001.0
747240,747242,747242,163145,2692,4,Run Lola Run (Lola rennt),16,4.06,Action|Crime,0,...,0,130827,104,3.99,2021,2,21,3,38,1998.0

In [ ]:
# shape data
df.shape

(999998, 38)

In [ ]:
# Total number of user in rating
print("Total number of user in rating",df["userId"].nunique())

Total number of user in rating 200902

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999998 entries, 0 to 999997
Data columns (total 38 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0.1        999998 non-null  int64
 1   Unnamed: 0          999998 non-null  int64
 2   userId              999998 non-null  int64
 3   movieId             999998 non-null  int64
 4   user_rating         999998 non-null  int64
 5   movie_title         999998 non-null  object
 6   user_rating_count   999998 non-null  int64
 7   user_rating_avg     999998 non-null  float64
 8   genres              999998 non-null  object
 9   (no genres listed)  999998 non-null  int64
 10  Action              999998 non-null  int64
 11  Adventure           999998 non-null  int64
 12  Animation           999998 non-null  int64
 13  Children            999998 non-null  int64
 14  Comedy              999998 non-null  int64
 15  Crime               999998 non-null  int64
 16  Documentary         999998 non-null  int64
 17  Drama               999998 non-null  int64
 18  Fantasy             999998 non-null  int64
 19  Film-Noir           999998 non-null  int64
 20  Horror              999998 non-null  int64
 21  IMAX                999998 non-null  int64
 22  Musical             999998 non-null  int64
 23  Mystery             999998 non-null  int64
 24  Romance             999998 non-null  int64
 25  Sci-Fi              999998 non-null  int64
 26  Thriller            999998 non-null  int64
 27  War                 999998 non-null  int64
 28  Western             999998 non-null  int64
 29  imdbId              999998 non-null  int64
 30  tmdbId              999998 non-null  int64
 31  movies_avg_rating   999998 non-null  float64
 32  year                999998 non-null  int64
 33  month               999998 non-null  int64
 34  day                 999998 non-null  int64
 35  hour                999998 non-null  int64
 36  minute              999998 non-null  int64
 37  movie_year          999998 non-null  float64
dtypes: float64(3), int64(33), object(2)
memory usage: 289.9+ MB

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0.1,999998.0,499999.619523,2.886755e+05,0.0,249999.25,499999.50,749999.75,999999.0
Unnamed: 0,999998.0,499999.619523,2.886755e+05,0.0,249999.25,499999.50,749999.75,999999.0
userId,999998.0,165550.272061,9.539911e+04,2.0,83007.50,166156.00,247830.00,330975.0
movieId,999998.0,28308.237140,4.995263e+04,1.0,1219.00,3259.00,39446.00,288983.0
user_rating,999998.0,3.388648,1.114852e+00,0.0,3.00,4.00,4.00,5.0
user_rating_count,999998.0,19.570835,3.931450e+01,1.0,4.00,10.00,23.00,980.0
user_rating_avg,999998.0,3.543628,6.511076e-01,0.5,3.16,3.54,4.00,5.0
(no genres listed),999998.0,0.001630,4.034040e-02,0.0,0.00,0.00,0.00,1.0
Action,999998.0,0.302573,4.593720e-01,0.0,0.00,0.00,1.00,1.0
Adventure,999998.0,0.238751,4.263208e-01,0.0,0.00,0.00,0.00,1.0
Animation,999998.0,0.068366,2.523733e-01,0.0,0.00,0.00,0.00,1.0
Children,999998.0,0.085578,2.797403e-01,0.0,0.00,0.00,0.00,1.0
Comedy,999998.0,0.350667,4.771790e-01,0.0,0.00,0.00,1.00,1.0
Crime,999998.0,0.168092,3.739484e-01,0.0,0.00,0.00,0.00,1.0
Documentary,999998.0,0.013152,1.139257e-01,0.0,0.00,0.00,0.00,1.0
Drama,999998.0,0.436734,4.959815e-01,0.0,0.00,0.00,1.00,1.0
Fantasy,999998.0,0.115212,3.192781e-01,0.0,0.00,0.00,0.00,1.0
Film-Noir,999998.0,0.009519,9.710003e-02,0.0,0.00,0.00,0.00,1.0
Horror,999998.0,0.076687,2.660945e-01,0.0,0.00,0.00,0.00,1.0
IMAX,999998.0,0.045950,2.093770e-01,0.0,0.00,0.00,0.00,1.0
Musical,999998.0,0.036451,1.874098e-01,0.0,0.00,0.00,0.00,1.0
Mystery,999998.0,0.081327,2.733370e-01,0.0,0.00,0.00,0.00,1.0
Romance,999998.0,0.173483,3.786648e-01,0.0,0.00,0.00,0.00,1.0
Sci-Fi,999998.0,0.178744,3.831383e-01,0.0,0.00,0.00,0.00,1.0
Thriller,999998.0,0.270944,4.444472e-01,0.0,0.00,0.00,1.00,1.0
War,999998.0,0.050156,2.182671e-01,0.0,0.00,0.00,0.00,1.0
Western,999998.0,0.018629,1.352110e-01,0.0,0.00,0.00,0.00,1.0
imdbId,999998.0,571345.907389,1.314448e+06,3.0,100519.00,120177.00,373074.00,27876411.0
tmdbId,999998.0,37390.447069,9.924302e+04,0.0,710.00,8077.00,13701.00,1141202.0
movies_avg_rating,999998.0,3.543623,4.810491e-01,0.5,3.28,3.63,3.89,5.0
year,999998.0,2009.697166,8.080374e+00,1995.0,2003.00,2010.00,2017.00,2023.0
month,999998.0,6.533393,3.509369e+00,1.0,3.00,7.00,10.00,12.0
day,999998.0,15.692518,8.810471e+00,1.0,8.00,16.00,23.00,31.0
hour,999998.0,12.484564,7.365225e+00,0.0,5.00,14.00,19.00,23.0
minute,999998.0,29.588048,1.730173e+01,0.0,15.00,30.00,45.00,59.0
movie_year,999998.0,1993.379905,6.562582e+01,0.0,1990.00,1997.00,2005.00,2023.0

In [ ]:
# Total number of null value
print("Total number of null value ",df.isna().sum().sum())

Total number of null value  0

In [ ]:
# Total number of Duplicates value
print("Total number of Duplicates value ",df.duplicated().sum())

Total number of Duplicates value  0

In [ ]:
# Total number of moives use in rating
print("Total number of moives use in df",df["movieId"].nunique())

Total number of moives use in df 27090

In [ ]:
# Total number of moives use in rating
print("Total number of user use in df",df["userId"].nunique())

Total number of user use in df 200902

In [ ]:
print(df["user_rating"].agg(["mean","max","min","var"]))

mean    3.388648
max     5.000000
min     0.000000
var     1.242896
Name: user_rating, dtype: float64

In [ ]:
print(df["user_rating_count"].agg(["mean","max","min","var"]))

mean      19.570835
max      980.000000
min        1.000000
var     1545.629807
Name: user_rating_count, dtype: float64

In [ ]:
print(df["movies_avg_rating"].agg(["mean","max","min","var"]))

mean    0.676361
max     1.000000
min     0.000000
var     0.011428
Name: movies_avg_rating, dtype: float64

#### 2.3.1 Rating Normalization Pipline

In [ ]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'userId', 'movieId', 'user_rating',
       'movie_title', 'user_rating_count', 'user_rating_avg', 'genres',
       '(no genres listed)', 'Action', 'Adventure', 'Animation', 'Children',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
       'Horror', 'IMAX', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller',
       'War', 'Western', 'imdbId', 'tmdbId', 'movies_avg_rating', 'year',
       'month', 'day', 'hour', 'minute', 'movie_year'],
      dtype='object')

In [ ]:
# Drop unnecessary columns (optional but helps simplify the pipeline)
df = df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'], errors='ignore')

In [ ]:
# Define features and target for normalization
features_to_normalize = ['user_rating', 'user_rating_count', 'user_rating_avg', 'movies_avg_rating']

In [ ]:
# Create a normalization pipeline using MinMaxScaler or StandardScaler
normalization_pipeline = Pipeline([
    ('scaler', MinMaxScaler())  # or use StandardScaler() for mean=0, std=1
])

In [ ]:
# Apply the pipeline to selected features
df[features_to_normalize] = normalization_pipeline.fit_transform(df[features_to_normalize])

In [ ]:
df.sample(5)

,userId,movieId,user_rating,movie_title,user_rating_count,user_rating_avg,genres,(no genres listed),Action,Adventure,...,Western,imdbId,tmdbId,movies_avg_rating,year,month,day,hour,minute,movie_year
509983,28986,1029,0.6,Dumbo,0.005107,0.777778,Animation|Children|Drama|Musical,0,0,0,...,0,33563,11360,0.651111,1999,10,14,1,8,1941.0
908961,315034,2517,0.6,Christine,0.015322,0.735556,Horror,0,0,0,...,0,85333,8769,0.613333,2021,5,31,16,6,1983.0
150304,199789,1653,0.8,Gattaca,0.010215,0.615556,Drama|Sci-Fi|Thriller,0,0,0,...,0,119177,782,0.740000,1999,12,14,16,48,1997.0
759467,65860,4734,0.6,Jay and Silent Bob Strike Back,0.010215,0.686667,Adventure|Comedy,0,0,1,...,0,261392,2294,0.646667,2008,10,30,20,8,2001.0
566738,27270,1200,0.8,Aliens,0.000000,0.777778,Action|Adventure|Horror|Sci-Fi,0,1,1,...,0,90605,679,0.773333,1999,11,16,15,47,1986.0

In [ ]:
df.to_csv("normalized_ratings.csv", index=False)